/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
#define ORYX_CONFIGURATOR
#define USB_SUSPEND_WAKEUP_DELAY 0

#define MK_KINETIC_SPEED

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 5

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

// #undef MOUSEKEY_MAX_SPEED
// #define MOUSEKEY_MAX_SPEED 15

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 30

#undef MOUSEKEY_BASE_SPEED
#define MOUSEKEY_BASE_SPEED 2000


#undef MOUSEKEY_WHEEL_INITIAL_MOVEMENTS
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 1

#undef MOUSEKEY_WHEEL_BASE_MOVEMENTS
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 2

#undef MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 2

#undef MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 1

#define FIRMWARE_VERSION u8"95YR3/ybNgB"
#define RGB_MATRIX_STARTUP_SPD 60

#define MIDI_ADVANCED
